console.log(typeof 5)
console.log(typeof true)
console.log(typeof undefined)
console.log(typeof 'Hamdan Hanafi')
console.log(typeof null)
console.log(typeof Symbol('just met'))
console.log(typeof {})
console.log(typeof [])
console.log(typeof function() {})